// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MixCRM.Models;

namespace MixCRM.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MixCRM.Models.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.HasKey("Id");

                    b.ToTable("Departmen");
                });

            modelBuilder.Entity("MixCRM.Models.Firma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama");

                    b.Property<string>("Adres");

                    b.Property<string>("Eposta");

                    b.Property<string>("FirmaAdi");

                    b.Property<string>("FirmaYetkilisi");

                    b.Property<string>("Tel");

                    b.Property<string>("Unvan");

                    b.HasKey("Id");

                    b.ToTable("Firmas");
                });

            modelBuilder.Entity("MixCRM.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.HasKey("Id");

                    b.ToTable("Kategoris");
                });

            modelBuilder.Entity("MixCRM.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<string>("Adres");

                    b.Property<string>("Cinsiyet");

                    b.Property<DateTime>("DTarih");

                    b.Property<string>("Email");

                    b.Property<int>("FirmaId");

                    b.Property<string>("Soyad");

                    b.Property<int>("TCKimlik");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("Musteris");
                });

            modelBuilder.Entity("MixCRM.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<string>("Adres");

                    b.Property<string>("Cinsiyet");

                    b.Property<DateTime>("DTarih");

                    b.Property<int>("DepartmanId");

                    b.Property<string>("Email");

                    b.Property<string>("Foto");

                    b.Property<string>("Soyad");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("MixCRM.Models.Satis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama");

                    b.Property<int>("MusteriId");

                    b.Property<int>("PersonelId");

                    b.Property<int>("SatisAdeti");

                    b.Property<string>("SatisAdi");

                    b.Property<DateTime>("SatisTarihi");

                    b.Property<int>("UrunId");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("UrunId");

                    b.ToTable("Satis");
                });

            modelBuilder.Entity("MixCRM.Models.Stok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StokAdet");

                    b.Property<int>("UrunId");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("Stoks");
                });

            modelBuilder.Entity("MixCRM.Models.Teklif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BasTarih");

                    b.Property<DateTime>("BitTarih");

                    b.Property<int>("MusteriId");

                    b.Property<int>("PersonelId");

                    b.Property<string>("TeklifAdi");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("PersonelId");

                    b.ToTable("Teklifs");
                });

            modelBuilder.Entity("MixCRM.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama");

                    b.Property<decimal>("AlisFiyati");

                    b.Property<int>("KategoriId");

                    b.Property<string>("Resim");

                    b.Property<decimal>("SatisFiyati");

                    b.Property<string>("UrunAdi");

                    b.Property<string>("UrunKodu");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Uruns");
                });

            modelBuilder.Entity("MixCRM.Models.Musteri", b =>
                {
                    b.HasOne("MixCRM.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MixCRM.Models.Personel", b =>
                {
                    b.HasOne("MixCRM.Models.Departman", "Departman")
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MixCRM.Models.Satis", b =>
                {
                    b.HasOne("MixCRM.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MixCRM.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MixCRM.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MixCRM.Models.Stok", b =>
                {
                    b.HasOne("MixCRM.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MixCRM.Models.Teklif", b =>
                {
                    b.HasOne("MixCRM.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MixCRM.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MixCRM.Models.Urun", b =>
                {
                    b.HasOne("MixCRM.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
